### ISSUE TITLE
This library uses an old version of Handlebars with an existing vulnerability

### ISSUE THREAD

**Issue by michaeljonathanblack** [YahooArchive/express-secure-handlebars#27]
See this blogpost, here: https://blog.sourceclear.com/handlebars_vulnerability_research_findings/

Which library has the more significant vulnerability? Is there a reason this library hasn't been updated to the latest version of Handlebars?

**Comment by adon-at-work** [comment]
that issue doesn't hurt [`secure-handlebars`](https://github.com/yahoo/secure-handlebars), and i.e., this `express-secure-handlebars`, which applies our own secure filters that accurately cook `=`.

if any one happens to have a chance to fix compatibility issues introduced by new versions of handlebars, I'm happy to review and merge them.
